version: '3.5'
services:
  localstack:
    container_name: glue-docker-sample-localstack
    image: localstack/localstack:2.3.2
    environment:
      - SERVICES=s3
      # dummy configure
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
     - ./data:/opt/code/localstack/data   #データをdockre側にマウント
     - ./localstack:/docker-entrypoint-initaws.d
    networks:
      - glue-network
  glue:
    container_name: glue-docker-sample-glue
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    volumes:
      - ./:/home/glue_user/workspace/jupyter_workspace
      - ./spark.conf:/home/glue_user/spark/conf/spark-defaults.conf
    environment:
      - DISABLE_SSL=true
      # dummy configure
      - AWS_REGION=ap-northeast-1
      - AWS_OUTPUT=json
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      # jupyterlabのポート
      - 8888:8888
      # spark uiのポート
      - 4040:4040
    networks:
      - glue-network
    command: /home/glue_user/jupyter/jupyter_start.sh
networks:
  glue-network:
    name: glue-network